import * as fs from 'fs';
import * as path from 'path';
import { compileFromFile } from 'json-schema-to-typescript';

async function compileSchemas() {
  const schemasDir = path.resolve(__dirname, '../schemas');
  const typesDir = path.resolve(__dirname, '../src/types/generated');

  if (!fs.existsSync(typesDir)) {
    fs.mkdirSync(typesDir, { recursive: true });
  }

  const schemaFiles = fs.readdirSync(schemasDir).filter(file => file.endsWith('.schema.json'));

  console.log(`Compiling ${schemaFiles.length} JSON Schemas to TypeScript...`);

  for (const schemaFile of schemaFiles) {
    const inputPath = path.join(schemasDir, schemaFile);
    const outputName = schemaFile.replace('.schema.json', '.d.ts');
    const outputPath = path.join(typesDir, outputName);

    try {
      const ts = await compileFromFile(inputPath, {
        bannerComment: '/* tslint:disable */\n/**\n* This file was automatically generated by json-schema-to-typescript.\n* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,\n* and run `npm run build:types` to regenerate this file.\n*/',
        unreachableDefinitions: true,
        strictIndexSignatures: false,
      });

      fs.writeFileSync(outputPath, ts, 'utf8');
      console.log(`  ✓ Compiled ${schemaFile} -> ${outputName}`);
    } catch (err) {
      console.error(`  ✗ Error compiling ${schemaFile}:`, err);
      process.exit(1);
    }
  }

  console.log('JSON Schema type compilation completed successfully.');
}

if (require.main === module) {
  compileSchemas().catch(err => {
    console.error('Fatal error during schema compilation:', err);
    process.exit(1);
  });
}
